In [25]:
import lifelib
import timeit
import pandas as pd
import numpy as np
import modelx as mx
import openpyxl

ex4 = mx.read_model('CashValue_ME_EX4')
Projection = ex4.Projection

timeit.timeit('ex4.Projection.result_pv()', globals=globals(), number=5)

0.6307517449999978

In [2]:
# Projection.model_point_table = Projection.model_point_1
table = Projection.model_point_table
# print("Number of model points: ", len(table))
# print("Model points: ", table)
# points = Projection.model_point_table_ext()
# points = Projection.model_point()["scen_id"].values[990:1010]
points = Projection.model_point()
print("model_point(): ", points)
print("with indices: ", points.index)

model_point():                   spec_id  age_at_entry sex  policy_term  policy_count  \
point_id scen_id                                                        
1        1             A            20   M           10           100   
         2             A            20   M           10           100   
         3             A            20   M           10           100   
         4             A            20   M           10           100   
         5             A            20   M           10           100   
...                  ...           ...  ..          ...           ...   
9        996           A            20   M           10           100   
         997           A            20   M           10           100   
         998           A            20   M           10           100   
         999           A            20   M           10           100   
         1000          A            20   M           10           100   

                  sum_assured  dur

In [3]:
pols = ex4.Projection.pols_if_at(12, "BEF_DECR")
print(np.shape(pols))
print(sum(pols))
print(pols)

(9000,)
900000.0
[100. 100. 100. ... 100. 100. 100.]


In [4]:
Projection.pols_if(1)

array([100., 100., 100., ..., 100., 100., 100.])

In [24]:
Projection.result_pv()["Net Cashflow"].groupby("point_id").mean().sum()

399477611.70743275

In [ ]:
print(ex4.Projection.max_proj_len())
ex4.Projection.pv_premiums()

121


array([50000000., 50000000., 50000000., ..., 30000000., 30000000.,
       30000000.])

In [ ]:
ex4.Projection.pols_new_biz(0)

array([100, 100, 100, ..., 100, 100, 100])

In [ ]:
inv = Projection.inv_return_mth(2)
print("Montlhy investment returns: ", inv)
print("with shape: ", np.shape(inv))

Montlhy investment returns:  [ 0.00807793 -0.00048898 -0.00302246 ... -0.00917993 -0.00629737
 -0.00596671]
with shape:  (9000,)


In [ ]:
Projection.result_pv()

Premiums  Death  Surrender      Maturity       Expenses  \
point_id scen_id                                                              
1        1        50000000.0    0.0        0.0  5.765190e+07  975895.951147   
         2        50000000.0    0.0        0.0  4.781116e+07  975895.951147   
         3        50000000.0    0.0        0.0  5.184905e+07  975895.951147   
         4        50000000.0    0.0        0.0  4.752251e+07  975895.951147   
         5        50000000.0    0.0        0.0  5.796074e+07  975895.951147   
...                      ...    ...        ...           ...            ...   
9        996      30000000.0    0.0        0.0  4.093654e+07  975895.951147   
         997      30000000.0    0.0        0.0  4.093654e+07  975895.951147   
         998      30000000.0    0.0        0.0  4.093654e+07  975895.951147   
         999      30000000.0    0.0        0.0  4.093654e+07  975895.951147   
         1000     30000000.0    0.0        0.0  4.093654e+07  975895.951147   

                  Commissions  Investment Income  Change in AV  Net Cashflow  
point_id scen_id                                                              
1        1          2500000.0       1.793864e+07  1.028674e+07 -3.475896e+06  
         2          2500000.0       7.638184e+06  9.827021e+06 -3.475896e+06  
         3          2500000.0       1.232610e+07  1.047706e+07 -3.475896e+06  
         4          2500000.0       7.454824e+06  9.932312e+06 -3.475896e+06  
         5          2500000.0       1.852191e+07  1.056117e+07 -3.475896e+06  
...                       ...                ...           ...           ...  
9        996        1500000.0       4.256529e+06  5.753036e+06 -1.490894e+07  
         997        1500000.0       7.287750e+06  6.331561e+06 -1.245624e+07  
         998        1500000.0       7.480443e+06  6.031063e+06 -1.196305e+07  
         999        1500000.0       1.098676e+07  6.345723e+06 -8.771397e+06  
         1000       1500000.0       8.407759e+06  6.481302e+06 -1.148598e+07  

[9000 rows x 9 columns]